av: Fix unused-lambda-capture warnings
frameworks/av/media/libmedia/omx/1.0/WOmxNode.cpp:50:33: error: lambda capture 'size' is not used [-Werror,-Wunused-lambda-capture]
            [&fnStatus, params, size](

frameworks/av/media/libmedia/omx/1.0/WOmxNode.cpp:148:33: error: lambda capture 'buffer_data' is not used [-Werror,-Wunused-lambda-capture]
            [&fnStatus, buffer, buffer_data, native_handle](

frameworks/av/services/camera/libcameraservice/device3/Camera3Device.cpp:142:11: error: lambda capture 'queue' is not required to be captured for this use [-Werror,-Wunused-lambda-capture]
        [&queue = mResultMetadataQueue](const auto& descriptor) {

Change-Id: Ic892eac2b9dd1058f4d4f2d24ebeefdaf3171867
Signed-off-by: joshuous <joshuous@gmail.com>